services:
  solar-monitor:
    build: 
      context: .
      network: host
    container_name: solar-monitor
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /SolarMonitor/solar-monitor.ini:/solar-monitor/solar-monitor.ini
      - /SolarMonitor/logs:/solar-monitor/solar-monitor
    restart: unless-stopped



